version: '3'
services:
    ddagent:
      image: datadog/agent:latest
      container_name: datadog-agent-ft
      env_file:
        - ~/sandbox.docker.env
      environment:
        - DD_APM_ENABLED=true
        - DD_LOGS_ENABLED=true
        - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
        - DD_APM_NON_LOCAL_TRAFFIC=true
        #- DD_CLOUD_PROVIDER_METADATA=aws
        - DD_TAGS="testing:here"
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc/:/host/proc/:ro
        - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      # labels:
      #   com.datadoghq.ad.logs: '[{"source":"testinghere"}]'
      ports:
        - "8126:8126"
      restart: on-failure
      depends_on: 
        - mysql_db
    mysql_db:
      image: mysql:8.0.20
      environment:
        MYSQL_ROOT_PASSWORD: 'example'
      volumes:
        - ./fortune-teller-mysql/conf.d:/etc/mysql/conf.d
        - ./fortune-teller-mysql/mysql-db-init-files:/docker-entrypoint-initdb.d
      labels:
        com.datadoghq.ad.check_names: '["mysql"]'
        com.datadoghq.ad.init_configs: '[{}]'
        com.datadoghq.ad.instances: '[{"server": "%%host%%", "user": "datadog","pass": "tacosandburritos"}]'
    express_server:
      build:
        dockerfile: Dockerfile
        context: ./fortune-teller-express
      depends_on: 
        - mysql_db
      environment: 
        - DD_ENV=prod
        - DD_AGENT_HOST=datadog-agent-ft
      ports:
        - '8080:8080'
    angular_web:
      build:
        dockerfile: Dockerfile
        context: ./fortune-teller-ng
      depends_on: 
        - express_server
      env_file:
        - ~/sandbox.docker.env
      ports:
        - '4200:4200'