version: '3'
services:
    mysql_db:
      image: mysql:8.0.20
      environment:
        MYSQL_ROOT_PASSWORD: 'example'
      volumes:
        - ./fortune-teller-mysql/conf.d:/etc/mysql/conf.d
        - ./fortune-teller-mysql/mysql-db-init-files:/docker-entrypoint-initdb.d
    express_server:
      build:
        dockerfile: Dockerfile
        context: ./fortune-teller-express
      depends_on: 
        - mysql_db
      ports:
        - '8080:8080'
    angular_web:
      build:
        dockerfile: Dockerfile
        context: ./fortune-teller-ng
      depends_on: 
        - express_server
      ports:
        - '4200:4200'